version: '3'
services:
  q_hamstery:
    hostname: q_hamstery
    container_name: q_hamstery
    image: q_hamstery:latest
    ports:
      - "8001:8001"
    environment:
      - PUID=
      - PGID=
      - TZ=
      - SECRET_KEY=
      - HOST_NAME=
      - HOST=
      - HAMSTERY_PORT=
    volumes:
      - /path/to/library:/home/library/
      - /path/to/app_data:/app/backend/app_data/
    restart: unless-stopped
