# Generated by Django 4.2.16 on 2024-12-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hamstery", "0019_openaititleparserlogs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hamsterysettings",
            name="openai_title_parser_prompt",
        ),
    ]
