# Generated by Django 4.2.16 on 2024-12-11 18:21

from django.db import migrations, models
import django.db.models.deletion


def migrate_poly(apps, schema_editor):
    TvDownload = apps.get_model('hamstery', 'TvDownload')
    MonitoredTvDownload = apps.get_model('hamstery', 'MonitoredTvDownload')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    tv_ct = ContentType.objects.get_for_model(TvDownload)
    mon_ct = ContentType.objects.get_for_model(MonitoredTvDownload)
    for download in TvDownload.objects.filter(polymorphic_ctype__isnull=True).all():
        if MonitoredTvDownload.objects.filter(tvdownload_ptr_id=download.id).exists():
            download.polymorphic_ctype = mon_ct
        else:
            download.polymorphic_ctype = tv_ct
        download.save()

class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("hamstery", "0022_rename_tvepisodedownload_tvdownload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvdownload",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.RunPython(migrate_poly, migrations.RunPython.noop)
    ]
