# Generated by Django 4.2.16 on 2024-12-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hamstery", "0022_rename_tvepisodedownload_tvdownload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoredtvdownload",
            name="auto_matched",
            field=models.BooleanField(default=False),
        ),
    ]
