# Generated by Django 4.2.16 on 2025-01-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hamstery", "0023_alter_monitoredtvdownload_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        related_name="downloads",
                        to="hamstery.tvseason",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hamstery.download",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonEpisodeDownload",
            fields=[
                (
                    "tvdownload_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hamstery.tvdownload",
                    ),
                ),
                (
                    "season_download",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        related_name="episodes",
                        to="hamstery.seasondownload",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("hamstery.tvdownload",),
        ),
    ]
