# Generated by Django 4.2.16 on 2025-01-13 22:55

from django.db import migrations, models
import logging

logger = logging.getLogger(__name__)

def migrate_openai_logs(apps, schema_edtior):
    OpenAITitleParserLogs = apps.get_model('hamstery', 'OpenAITitleParserLogs')
    for log in OpenAITitleParserLogs.objects.all():
        if log.episode_number != 0:
            log.result = { "episode": log.episode_number }
            log.save()


def migrate_openai_logs_reverse(apps, schema_edtior):
    OpenAITitleParserLogs = apps.get_model('hamstery', 'OpenAITitleParserLogs')
    for log in OpenAITitleParserLogs.objects.all():
        if log.result and "episode" in log.result:
            try:
                log.episode_number = int(log.result["episode"])
                log.save()
            except:
                pass
        


class Migration(migrations.Migration):

    dependencies = [
        ("hamstery", "0024_seasondownload_seasonepisodedownload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaititleparserlogs",
            name="result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_openai_logs, migrate_openai_logs_reverse),
        migrations.RemoveField(
            model_name="openaititleparserlogs",
            name="episode_number",
        ),
    ]
